# BBO Datasheet
## 1. Motivation
This dataset is an attempt to find the global maximum for each of the eight unknown functions in the black-box optimization challenge. The project is based on the 2020 NeurIPS black-box optimization challenge. The initial datapoints were given to us by Imperial College, while the remaining thirteen datapoints are from my personal queries.
## 2. Composition
The dataset consists of datapoints for eight functions, with the functions ranging in size from two dimensions (two input variables per output) to eight dimensions (eight input variables per output). The initial datapoints given by Imperial College range from 10 to 40 input/output combinations. The remaining 13 input combinations are generated by yours truly, while the remaining 13 output results are generated by Imperial College as a response to my inputs. Each input must be in the range [0.000000, 0.999999] while the outputs have no bounds.
## 3. Collection Process
The queries were generated using Bayesian optimization with an ensemble of models. The four models were: GaussianProcessRegressor surrogate model with Upper Confidence Bound acquisition function, GaussianProcessRegressor surrogate model with Expected Improvement acquisition function, Sequential Model-based Algorithm Configuration (SMAC), and BoTorch. I developed the models in that order, with the GaussianProcessRegressor/UCB model being the first, sequentially adding the rest of the models. 
## 4. Preprocessing
For the first four weeks, I didn't apply any preprocessing other than normalize_y=True in the GaussianProcessRegressor. Starting in week five, I applied a custom non-linear transformation to the output of Function 1 due to the extreme magnitude differences in the raw outputs. Starting in week eight, I applied the Yeo-Johnson PowerTransformer to the outputs for Functions 2-8 to reduce heteroscedasticity; this was found to be beneficial by HEBO, the winners of the 2020 NeurIPS black-box optimization challenge.
## 5. Distribution and Maintenance
The initial input/output combinations are maintained by Imperial College. The subsequent 13 input/output combinations are in my local Jupyter notebook environment.
